require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GroupMapsController do

  # This should return the minimal set of attributes required to create a valid
  # GroupMap. As you add validations to GroupMap, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GroupMapsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all group_maps as @group_maps" do
      group_map = GroupMap.create! valid_attributes
      get :index, {}, valid_session
      assigns(:group_maps).should eq([group_map])
    end
  end

  describe "GET show" do
    it "assigns the requested group_map as @group_map" do
      group_map = GroupMap.create! valid_attributes
      get :show, {:id => group_map.to_param}, valid_session
      assigns(:group_map).should eq(group_map)
    end
  end

  describe "GET new" do
    it "assigns a new group_map as @group_map" do
      get :new, {}, valid_session
      assigns(:group_map).should be_a_new(GroupMap)
    end
  end

  describe "GET edit" do
    it "assigns the requested group_map as @group_map" do
      group_map = GroupMap.create! valid_attributes
      get :edit, {:id => group_map.to_param}, valid_session
      assigns(:group_map).should eq(group_map)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GroupMap" do
        expect {
          post :create, {:group_map => valid_attributes}, valid_session
        }.to change(GroupMap, :count).by(1)
      end

      it "assigns a newly created group_map as @group_map" do
        post :create, {:group_map => valid_attributes}, valid_session
        assigns(:group_map).should be_a(GroupMap)
        assigns(:group_map).should be_persisted
      end

      it "redirects to the created group_map" do
        post :create, {:group_map => valid_attributes}, valid_session
        response.should redirect_to(GroupMap.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved group_map as @group_map" do
        # Trigger the behavior that occurs when invalid params are submitted
        GroupMap.any_instance.stub(:save).and_return(false)
        post :create, {:group_map => {}}, valid_session
        assigns(:group_map).should be_a_new(GroupMap)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GroupMap.any_instance.stub(:save).and_return(false)
        post :create, {:group_map => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested group_map" do
        group_map = GroupMap.create! valid_attributes
        # Assuming there are no other group_maps in the database, this
        # specifies that the GroupMap created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GroupMap.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => group_map.to_param, :group_map => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested group_map as @group_map" do
        group_map = GroupMap.create! valid_attributes
        put :update, {:id => group_map.to_param, :group_map => valid_attributes}, valid_session
        assigns(:group_map).should eq(group_map)
      end

      it "redirects to the group_map" do
        group_map = GroupMap.create! valid_attributes
        put :update, {:id => group_map.to_param, :group_map => valid_attributes}, valid_session
        response.should redirect_to(group_map)
      end
    end

    describe "with invalid params" do
      it "assigns the group_map as @group_map" do
        group_map = GroupMap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GroupMap.any_instance.stub(:save).and_return(false)
        put :update, {:id => group_map.to_param, :group_map => {}}, valid_session
        assigns(:group_map).should eq(group_map)
      end

      it "re-renders the 'edit' template" do
        group_map = GroupMap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GroupMap.any_instance.stub(:save).and_return(false)
        put :update, {:id => group_map.to_param, :group_map => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested group_map" do
      group_map = GroupMap.create! valid_attributes
      expect {
        delete :destroy, {:id => group_map.to_param}, valid_session
      }.to change(GroupMap, :count).by(-1)
    end

    it "redirects to the group_maps list" do
      group_map = GroupMap.create! valid_attributes
      delete :destroy, {:id => group_map.to_param}, valid_session
      response.should redirect_to(group_maps_url)
    end
  end

end
